#!/usr/bin/env python3
"""Octobots memory CLI — per-role curated entries + daily logs.

Layout under .agents/memory/<role>/ (IDE-neutral — same path under Claude,
Cursor, Gemini CLI, Copilot CLI, Windsurf, or Octobots):
    MEMORY.md            curated index (one line per typed entry)
    <name>.md            individual typed entries (frontmatter + body)
    project_briefing.md  seeded by scout at install time (type: project)
    daily/YYYY-MM-DD.md  episodic logs, append-only timestamped lines
    snapshot.md          regenerated by `snapshot` — what AGENT.md @-imports

Commands (resolve role from --role or $OCTOBOTS_ID):

    log "text"                                  append to today's daily log
    write <name> --type T --description D       create/replace a curated entry
        [--content "..." | reads stdin]
    read [--days N]                             dump last N days of daily logs + index
    snapshot                                    regenerate snapshot.md

All output is human-readable on stdout. Errors → stderr, non-zero exit.
"""
from __future__ import annotations

import argparse
import datetime as _dt
import os
import re
import sys
from pathlib import Path


VALID_TYPES = {"user", "feedback", "project", "reference"}
SNAPSHOT_DAYS_DEFAULT = 3
SNAPSHOT_MAX_BYTES = 32_000  # safety cap so snapshot.md never blows up the prompt


def project_root() -> Path:
    """Project root = first ancestor of CWD containing .agents/ or .octobots/, else CWD."""
    cwd = Path.cwd().resolve()
    for p in [cwd, *cwd.parents]:
        if (p / ".agents").is_dir() or (p / ".octobots").is_dir():
            return p
    return cwd


def role_dir(role: str) -> Path:
    """Canonical per-role memory dir. Auto-migrates legacy paths on first use.

    Canonical: .agents/memory/<role>/
    Legacy, migrated on first access:
        .octobots/memory/<role>/   (old supervisor path)
        .claude/memory/<role>/     (old sdlc-skills path)
        .claude/memory/<role>.md   (old flat project-seeder file — becomes
                                    project_briefing.md curated entry)
    """
    root = project_root()
    canonical = root / ".agents" / "memory" / role
    if canonical.exists():
        return canonical

    for legacy in [root / ".octobots" / "memory" / role,
                   root / ".claude" / "memory" / role]:
        if legacy.is_dir():
            canonical.parent.mkdir(parents=True, exist_ok=True)
            legacy.rename(canonical)
            return canonical

    # Legacy flat file — wrap as project_briefing.md curated entry
    legacy_flat = root / ".claude" / "memory" / f"{role}.md"
    if legacy_flat.is_file():
        canonical.mkdir(parents=True, exist_ok=True)
        body = legacy_flat.read_text(encoding="utf-8", errors="replace")
        briefing = canonical / "project_briefing.md"
        briefing.write_text(
            "---\n"
            "name: Project briefing\n"
            "description: Scout-seeded project overview (migrated from legacy flat file)\n"
            "type: project\n"
            "---\n\n"
            f"{body}"
        )
        index = canonical / "MEMORY.md"
        index.write_text(
            f"# Memory index — {role}\n\n"
            "- [Project briefing](project_briefing.md) — Scout-seeded project overview\n"
        )
        legacy_flat.unlink()
        return canonical

    return canonical


def daily_path(role: str, date: _dt.date | None = None) -> Path:
    date = date or _dt.date.today()
    return role_dir(role) / "daily" / f"{date.isoformat()}.md"


def index_path(role: str) -> Path:
    return role_dir(role) / "MEMORY.md"


def snapshot_path(role: str) -> Path:
    return role_dir(role) / "snapshot.md"


def ensure_role_dir(role: str) -> None:
    (role_dir(role) / "daily").mkdir(parents=True, exist_ok=True)


def cmd_log(role: str, text: str) -> int:
    if not text.strip():
        print("error: empty log text", file=sys.stderr)
        return 2
    ensure_role_dir(role)
    fp = daily_path(role)
    now = _dt.datetime.now().strftime("%H:%M")
    with fp.open("a", encoding="utf-8") as f:
        if fp.stat().st_size == 0:
            f.write(f"# Daily log — {_dt.date.today().isoformat()}\n\n")
        f.write(f"- [{now}] {text.strip()}\n")
    print(f"logged → {fp}")
    return 0


def slugify(name: str) -> str:
    s = re.sub(r"[^a-zA-Z0-9_-]+", "_", name.strip().lower())
    return s.strip("_") or "memory"


def cmd_write(role: str, name: str, mem_type: str, description: str, content: str) -> int:
    if mem_type not in VALID_TYPES:
        print(f"error: --type must be one of {sorted(VALID_TYPES)}", file=sys.stderr)
        return 2
    if not description.strip():
        print("error: --description is required", file=sys.stderr)
        return 2
    if not content.strip():
        print("error: empty content (pass --content or pipe via stdin)", file=sys.stderr)
        return 2

    ensure_role_dir(role)
    slug = slugify(name)
    entry = role_dir(role) / f"{slug}.md"
    body = (
        f"---\n"
        f"name: {name}\n"
        f"description: {description.strip()}\n"
        f"type: {mem_type}\n"
        f"---\n\n"
        f"{content.strip()}\n"
    )
    entry.write_text(body, encoding="utf-8")

    # Update index — replace existing line or append.
    idx = index_path(role)
    line = f"- [{name}]({slug}.md) — {description.strip()}\n"
    if idx.exists():
        existing = idx.read_text(encoding="utf-8").splitlines(keepends=True)
        kept = [
            ln for ln in existing
            if not re.match(rf"^\s*-\s*\[[^\]]+\]\({re.escape(slug)}\.md\)", ln)
        ]
        # Ensure header on first run.
        if not any(ln.startswith("# ") for ln in kept):
            kept = [f"# Memory index — {role}\n", "\n", *kept]
        kept.append(line)
        idx.write_text("".join(kept), encoding="utf-8")
    else:
        idx.write_text(f"# Memory index — {role}\n\n{line}", encoding="utf-8")

    print(f"wrote → {entry}")
    return 0


def cmd_read(role: str, days: int) -> int:
    days = max(1, days)
    today = _dt.date.today()
    out: list[str] = []

    idx = index_path(role)
    if idx.is_file():
        out.append(idx.read_text(encoding="utf-8").rstrip())
        out.append("")

    out.append(f"## Daily log (last {days} day{'s' if days != 1 else ''})")
    out.append("")
    found_any = False
    for delta in range(days):
        d = today - _dt.timedelta(days=delta)
        fp = daily_path(role, d)
        if fp.is_file():
            found_any = True
            out.append(fp.read_text(encoding="utf-8").rstrip())
            out.append("")
    if not found_any:
        out.append("_(no daily log entries)_")

    print("\n".join(out).rstrip())
    return 0


def cmd_snapshot(role: str, days: int) -> int:
    """Regenerate snapshot.md combining index + recent daily logs.

    The supervisor calls this before every role spawn so AGENT.md's
    @-import resolves to current memory at session start.
    """
    ensure_role_dir(role)
    parts: list[str] = []
    parts.append(f"# Memory snapshot — {role}")
    parts.append(f"_Generated {_dt.datetime.now().isoformat(timespec='seconds')}._")
    parts.append("")

    idx = index_path(role)
    if idx.is_file():
        parts.append("## Curated memory")
        parts.append("")
        parts.append(idx.read_text(encoding="utf-8").rstrip())
        parts.append("")
        # Inline each entry's body so the snapshot is self-contained.
        for entry in sorted(role_dir(role).glob("*.md")):
            if entry.name in {"MEMORY.md", "snapshot.md"}:
                continue
            try:
                parts.append(f"### {entry.stem}")
                parts.append("")
                parts.append(entry.read_text(encoding="utf-8").rstrip())
                parts.append("")
            except OSError:
                continue

    today = _dt.date.today()
    daily_section: list[str] = []
    for delta in range(days):
        d = today - _dt.timedelta(days=delta)
        fp = daily_path(role, d)
        if fp.is_file():
            daily_section.append(fp.read_text(encoding="utf-8").rstrip())
            daily_section.append("")
    if daily_section:
        parts.append(f"## Recent daily log (last {days} day{'s' if days != 1 else ''})")
        parts.append("")
        parts.extend(daily_section)

    body = "\n".join(parts).rstrip() + "\n"
    if len(body.encode("utf-8")) > SNAPSHOT_MAX_BYTES:
        # Truncate from the top of the daily-log section so curated memory survives.
        keep = body[: SNAPSHOT_MAX_BYTES // 2]
        body = (
            keep.rstrip()
            + "\n\n_(snapshot truncated — exceeded budget; trim daily logs or curate them)_\n"
        )
    snapshot_path(role).write_text(body, encoding="utf-8")
    print(f"snapshot → {snapshot_path(role)} ({len(body)} bytes)")
    return 0


def resolve_role(arg: str | None) -> str:
    role = arg or os.environ.get("OCTOBOTS_ID", "")
    if not role:
        print("error: --role required (or set OCTOBOTS_ID)", file=sys.stderr)
        sys.exit(2)
    return role


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(prog="memory.py", description="Octobots per-role memory")
    p.add_argument("--role", help="role name (default: $OCTOBOTS_ID)")
    sub = p.add_subparsers(dest="cmd", required=True)

    sp_log = sub.add_parser("log", help="append a timestamped line to today's daily log")
    sp_log.add_argument("text")

    sp_write = sub.add_parser("write", help="create/replace a curated typed memory entry")
    sp_write.add_argument("name")
    sp_write.add_argument("--type", dest="mem_type", required=True, choices=sorted(VALID_TYPES))
    sp_write.add_argument("--description", required=True)
    sp_write.add_argument("--content", default=None,
                          help="content body; if omitted, read from stdin")

    sp_read = sub.add_parser("read", help="dump curated index + last N days of daily logs")
    sp_read.add_argument("--days", type=int, default=SNAPSHOT_DAYS_DEFAULT)

    sp_snap = sub.add_parser("snapshot", help="regenerate snapshot.md (called by supervisor)")
    sp_snap.add_argument("--days", type=int, default=SNAPSHOT_DAYS_DEFAULT)

    args = p.parse_args(argv)
    role = resolve_role(args.role)

    if args.cmd == "log":
        return cmd_log(role, args.text)
    if args.cmd == "write":
        content = args.content
        if content is None:
            content = sys.stdin.read()
        return cmd_write(role, args.name, args.mem_type, args.description, content)
    if args.cmd == "read":
        return cmd_read(role, args.days)
    if args.cmd == "snapshot":
        return cmd_snapshot(role, args.days)
    return 2


if __name__ == "__main__":
    sys.exit(main())
